<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Prod1info.aspx.cs" Inherits="Mini_Project.Prod1info" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Product Details</title>

    <style type="text/css">

        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #111122;
        }

        .main-panel {
            min-height: 100vh;
            background-image: url('Images/allbgprod.jpg');
            background-size: cover;
            background-position: center;
            padding: 50px 0;
        }

        .product-area {
            width: 90%;
            max-width: 1100px;
            margin: auto;

            display: flex;
            align-items: flex-start;
            justify-content: center;
            gap: 40px;
        }

        /* PRODUCT IMAGE */

        .product-image {
            width: 400px;
            height: 400px;

            object-fit: contain;

            background-color: white;
            padding: 15px;

            border-radius: 10px;

            flex-shrink: 0;
        }

        /* PRODUCT CONTENT */

        .product-info {
            width: 550px;

            padding: 25px;

            background-color: #151525;

            border: 2px solid #7137d9;
            border-radius: 10px;

            color: white;

            font-size: 17px;
            line-height: 1.6;

            display: block;

            overflow: visible;
        }

        /* Content generated by Label1 */

        .product-info h1 {
            color: #00ffff;
            font-size: 30px;
            margin-top: 0;
            margin-bottom: 15px;
        }

        .product-info h2 {
            color: #00ffff;
            font-size: 23px;
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .product-info b {
            color: #ffffff;
        }


        /* SMALL SCREEN */

        @media screen and (max-width: 900px) {

            .product-area {
                flex-direction: column;
                align-items: center;
            }

            .product-image {
                width: 300px;
                height: 300px;
            }

            .product-info {
                width: 90%;
                max-width: 550px;
            }
        }

        .auto-style1 {
            z-index: 1;
            left: 1px;
            top: 28px;
            position: absolute;
            font-size: 17pt;
            font-weight: 700;
            color: #66FFFF;
            text-decoration: underline;
            height: 34px;
            width: 227px;
        }

    </style>
</head>

<body>

<form id="form1" runat="server">

    <asp:Panel
        ID="Panel1"
        runat="server"
        CssClass="main-panel">

        <div class="product-area">

            <!-- PRODUCT IMAGE -->

            <asp:Image
                ID="Image1"
                runat="server"
                ImageUrl="~/Images/prod1.jpg"
                CssClass="product-image" />


            <!-- PRODUCT INFORMATION -->

            <asp:Label
                ID="Label1"
                runat="server"
                CssClass="product-info">
            </asp:Label>

            <asp:HyperLink ID="HyperLink1" runat="server" CssClass="auto-style1" NavigateUrl="~/Product.aspx">Continue Shopping</asp:HyperLink>

        </div>

    </asp:Panel>

</form>

</body>
</html>